/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openZeppelin from "./open-zeppelin";
export type { openZeppelin };
export type { Airdrop } from "./Airdrop";
export type { DividendsPool } from "./DividendsPool";
export type { FoxToken } from "./FoxToken";
export * as factories from "./factories";
export { Airdrop__factory } from "./factories/Airdrop__factory";
export { DividendsPool__factory } from "./factories/DividendsPool__factory";
export { FoxToken__factory } from "./factories/FoxToken__factory";
export type { ERC20 } from "./open-zeppelin/ERC20";
export { ERC20__factory } from "./factories/open-zeppelin/ERC20__factory";
export type { IERC20Metadata } from "./open-zeppelin/extensions/IERC20Metadata";
export { IERC20Metadata__factory } from "./factories/open-zeppelin/extensions/IERC20Metadata__factory";
export type { IERC20 } from "./open-zeppelin/IERC20";
export { IERC20__factory } from "./factories/open-zeppelin/IERC20__factory";
export type { Ownable } from "./open-zeppelin/Ownable";
export { Ownable__factory } from "./factories/open-zeppelin/Ownable__factory";
